name: Build, Push to Docker Hub, and Deploy Nginx Website (with Localhost Check)

on:
  push:
    branches: [ main ]

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}  
  DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}  

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Verify for localhost in ./src/api.js
        run: |
          grep -r --line-number localhost ./src/api.js
          if [ $? -eq 0 ]; then
            echo "ERRO: Encontrado 'localhost' em ./src/api.js. TIRA O LOCALHOST COR NO!"
            exit 1  # Stop the workflow if localhost is found
          fi

      - name: Login to Docker Hub (using encrypted credentials)
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push image to Docker Hub
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/nginx-website:latest .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/nginx-website:latest

      - name: Deploy to AWS (replace with your specific deployment steps)
        run: |  # Only the 'run' key remains
          aws ecs register-task-definition --family nginx-website --network-mode awsvpc --cpu "256" --memory "512" --container-definitions "[{
              "name": "nginx-container",
              "image": "{{ secrets.DOCKERHUB_USERNAME }}/nginx-website:latest",  # Changed image name
              "essential": true,
              "portMappings": [{
                  "containerPort": 80,
                  "hostPort": 80
              }],
              "environment": []
          }]"
          aws ecs run-task --cluster my-cluster --launch-type FARGATE --task-definition nginx-website
