name: Build, Push to Docker Hub, and Deploy Nginx Website (with Localhost Check)

on:
  push:
    branches: [ main ]

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}  
  DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}  

jobs:
  BuildAndDeploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub (using encrypted credentials)
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push image to Docker Hub
        run: |
          docker build -t leonardopradosptech/changer:latest .
          docker push leonardopradosptech/changer:latest

      - uses: appleboy/ssh-action@v1.0.3
        with:
          host: "44.217.150.7"
          username: "ubuntu"
          key: ${{ secrets.CHANGER }}
          script: |
            sudo docker pull leonardopradosptech/changer
            sudo docker run -p 80:80 -p 8080:8080 -p 443:443 -d leonardopradosptech/changer