name: Build, Push to Docker Hub, and Deploy Nginx Website (with Localhost Check)

on:
  push:
    branches: [ main ]

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}  
  DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}  

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3


      # - name: Verify for 'localhost' in src directory
      #   run: |
      #     if grep -rl 'localhost' /home/runner/work/Site-Institucional/Site-Institucional/src/; then
      #       echo "TIRA O LOCALHOST CORNO"
      #       grep -rl 'localhost' /home/runner/work/Site-Institucional/Site-Institucional/src/
      #       exit 1
      #     else
      #       echo "No 'localhost' references found in /home/runner/work/Site-Institucional/Site-Institucional/src/."
      #     fi

      - name: Login to Docker Hub (using encrypted credentials)
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push image to Docker Hub
        run: |
          docker build -t leonardopradosptech/changer:latest .
          docker push leonardopradosptech/changer:latest

    steps:
      - uses: appleboy/ssh-action@v1.0.3  # You can choose a different version
        with:
          host: "44.217.150.7"  # Server hostname
          username: "ubuntu"  # Username for server
          key: ${{ secrets.CHANGER }}  # Reference your PEM key secret
          script: whoami  # Command to run on the server

      - name: Pull the image (on the server)
        run: |
          ssh ${{ steps.login.outputs.user }}@${{ steps.login.outputs.host }} docker pull leonardopradosptech/changer

      - name: Run the container (on the server)
        run: |
          ssh ${{ steps.login.outputs.user }}@${{ steps.login.outputs.host }} docker run -p 80:80 -p 8080:8080 -p 443:443 leonardopradosptech/changer
